# Generated by Django 5.0.2 on 2024-02-27 04:29

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_delete_establishment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='phone',
        ),
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media'),
        ),
    ]
