# Generated by Django 4.1.3 on 2024-03-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
