# Generated by Django 5.0.2 on 2024-02-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='event_id',
        ),
    ]
