# Generated by Django 4.1.3 on 2024-03-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_location_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
