# Generated by Django 5.0.2 on 2024-03-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
