# Generated by Django 4.1.3 on 2024-03-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_establishment_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='is_featured',
        ),
    ]
