# Generated by Django 4.1.3 on 2024-03-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0004_establishment_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
