# Generated by Django 5.0.2 on 2024-02-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_user_id'),
        ('users', '0007_gender_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.ManyToManyField(to='users.userprofile'),
        ),
    ]
